name: Terraform CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.5

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform fmt
      run: terraform fmt -check
      working-directory: environments/demo

    - name: Terraform Init
      run: terraform init
      working-directory: environments/demo

    - name: Terraform Validate
      run: terraform validate
      working-directory: environments/demo

    - name: Terraform Plan
      run: terraform plan -out=plan.tfout
      working-directory: environments/demo
